export type SiteImage = {
  src: string;
  alt: string;
  width: number;
  height: number;
};

export const IMAGES = {
  hero: {
    src: "/images/hero-leman.jpg",
    alt: "Le Léman au crépuscule, quais de Genève, lumières de tungstène sur l’eau.",
    width: 1280,
    height: 720,
  },
  geneve: {
    src: "/images/geneve-jet.jpg",
    alt: "Le Jet d’eau de Genève et le pont du Mont-Blanc à l’heure bleue.",
    width: 1280,
    height: 720,
  },
  lavaux: {
    src: "/images/lavaux.jpg",
    alt: "Terrasses de Lavaux au-dessus du lac Léman, fin d’automne.",
    width: 1280,
    height: 720,
  },
  vaud: {
    src: "/images/vaud-lausanne.jpg",
    alt: "Lausanne et le lac vus d’une terrasse au crépuscule, canton de Vaud.",
    width: 1280,
    height: 720,
  },
  banque: {
    src: "/images/banque-facade.jpg",
    alt: "Façade de pierre et poignée de laiton, institution de prévoyance à Genève.",
    width: 1152,
    height: 864,
  },
  assurance: {
    src: "/images/assurance-bureau.jpg",
    alt: "Bureau d’assurance : stylo, chemise crème, lumière du nord.",
    width: 1152,
    height: 864,
  },
  pillar3a: {
    src: "/images/pilier-3a.jpg",
    alt: "Coffres de dépôt dans une lumière de bronze : l’épargne liée du 3a.",
    width: 1152,
    height: 864,
  },
  pillar3b: {
    src: "/images/pilier-3b.jpg",
    alt: "Villa au bord du Léman le soir : la prévoyance libre du 3b.",
    width: 1152,
    height: 864,
  },
  conseiller: {
    src: "/images/portrait-conseiller.jpg",
    alt: "Conseiller en prévoyance, portrait éditorial dans une cour genevoise.",
    width: 864,
    height: 1152,
  },
  cliente: {
    src: "/images/portrait-cliente.jpg",
    alt: "Portrait éditorial dans une arcade de Genève.",
    width: 864,
    height: 1152,
  },
  couple: {
    src: "/images/portrait-couple.jpg",
    alt: "Couple sur un quai de Genève, regard vers le lac.",
    width: 1152,
    height: 864,
  },
  frontalier: {
    src: "/images/frontalier.jpg",
    alt: "Quai de gare à Genève à l’aube, trajet de frontalier.",
    width: 1280,
    height: 720,
  },
  enfant: {
    src: "/images/epargne-enfant.jpg",
    alt: "Jouets en bois près d’une fenêtre, lumière du matin, épargne enfant.",
    width: 1152,
    height: 864,
  },
  merci: {
    src: "/images/remerciement-aube.jpg",
    alt: "Aube brumeuse sur le Léman, ponton de bois.",
    width: 1280,
    height: 720,
  },
  mixte: {
    src: "/images/mixte-cle.jpg",
    alt: "Clé de laiton et ruban de soie sur lin, tension entre lié et libre.",
    width: 1152,
    height: 864,
  },
  avs: {
    src: "/images/avs-colonnade.jpg",
    alt: "Colonnade de grès et bâtiment à coupole : lire le tableau OFAS.",
    width: 1152,
    height: 864,
  },
  renteAvs: {
    src: "/images/cover-rente-avs.jpg",
    alt: "Banc de bois face au Léman : rente du 1er pilier AVS.",
    width: 1152,
    height: 864,
  },
  lpp: {
    src: "/images/lpp-dossiers.jpg",
    alt: "Dossiers crème et lunettes sur chêne, deuxième pilier LPP.",
    width: 1152,
    height: 864,
  },
  alpes: {
    src: "/images/horizon-alpes.jpg",
    alt: "Crête alpine au dernier jour, horizon de long terme.",
    width: 1152,
    height: 864,
  },
  laiton: {
    src: "/images/detail-laiton.jpg",
    alt: "Heurtoir de laiton sur bois vert, détail d’un portail genevois.",
    width: 1152,
    height: 864,
  },
  papier: {
    src: "/images/texture-papier.jpg",
    alt: "Papier vergé crème, fibre visible.",
    width: 1280,
    height: 720,
  },
  deductions: {
    src: "/images/cover-deductions.jpg",
    alt: "Chemise de lin crème, stylo vert et sceau de cire : déductions fiscales du 3e pilier.",
    width: 1152,
    height: 864,
  },
  independant: {
    src: "/images/cover-independant.jpg",
    alt: "Établi d’indépendant à Genève : tablier de cuir, balance de laiton, lumière du matin.",
    width: 1152,
    height: 864,
  },
  plafonds: {
    src: "/images/cover-plafonds.jpg",
    alt: "Deux bocaux de verre, un petit et un grand, remplis de pièces : plafonds 3a.",
    width: 1152,
    height: 864,
  },
  fribourg: {
    src: "/images/cover-fribourg.jpg",
    alt: "Vieille ville de Fribourg et pont sur la Sarine, fin d’automne.",
    width: 1280,
    height: 720,
  },
  depart: {
    src: "/images/cover-depart.jpg",
    alt: "Valise de cuir sur un quai de gare suisse à l’aube : départ et retrait du 3a.",
    width: 1152,
    height: 864,
  },
  combiner: {
    src: "/images/cover-combiner.jpg",
    alt: "Coffret de laiton fermé et bourse de lin ouverte : combiner 3a et 3b.",
    width: 1152,
    height: 864,
  },
  frais: {
    src: "/images/cover-frais.jpg",
    alt: "Loupe de laiton et piles de pièces : frais d’un 3a en banque ou en assurance.",
    width: 1152,
    height: 864,
  },
  decembre: {
    src: "/images/cover-decembre.jpg",
    alt: "Enveloppe cachetée et brin de sapin : versement 3a avant la fin d’année.",
    width: 1152,
    height: 864,
  },
  mixteContrat: {
    src: "/images/cover-mixte-jarre.jpg",
    alt: "Bocal de pièces, pomme et écharpe de laine sur noyer : contrat mixte, épargne et protection.",
    width: 1152,
    height: 864,
  },
  risque: {
    src: "/images/cover-risque-vase.jpg",
    alt: "Vase blanc vide dans un couloir clair : risque pur, sans capital constitué.",
    width: 1152,
    height: 864,
  },
  liberation: {
    src: "/images/cover-liberation.jpg",
    alt: "Chaise vide et couverture de laine : libération du paiement des primes.",
    width: 1152,
    height: 864,
  },
  passage: {
    src: "/images/cover-passage.jpg",
    alt: "Boîte d’archives sur un banc : libre passage LPP entre deux emplois.",
    width: 1152,
    height: 864,
  },
  compteLp: {
    src: "/images/cover-compte-lp.jpg",
    alt: "Portefeuille de cuir et cartes vierges sur marbre : compte de libre passage.",
    width: 1152,
    height: 864,
  },
  contact: {
    src: "/images/cover-contact.jpg",
    alt: "Téléphone de bakélite et tasse de thé, bureau face au lac.",
    width: 1152,
    height: 864,
  },
  confidentialite: {
    src: "/images/cover-confidentialite.jpg",
    alt: "Cadenas de laiton sur une enveloppe de lin : confidentialité.",
    width: 1152,
    height: 864,
  },
  declaration: {
    src: "/images/cover-declaration.jpg",
    alt: "Dossier vert fermé d’un sceau de cire : ancienne offre de déclaration d’impôt.",
    width: 1152,
    height: 864,
  },
  mentions: {
    src: "/images/cover-mentions.jpg",
    alt: "Plaque de pierre nue sur une façade genevoise : mentions légales.",
    width: 1152,
    height: 864,
  },
  apropos: {
    src: "/images/cover-apropos.jpg",
    alt: "Deux chaises vides face au Léman : le bureau du comparatif.",
    width: 1152,
    height: 864,
  },
  arbitrage: {
    src: "/images/cover-arbitrage.jpg",
    alt: "Fragment de colonne et chemise de cuir : choisir banque ou assurance.",
    width: 1152,
    height: 864,
  },
  tou: {
    src: "/images/cover-tou.jpg",
    alt: "Couloir d’un office fiscal, verrière dépolie : taxation ordinaire ultérieure.",
    width: 1152,
    height: 864,
  },
  retraitImpot: {
    src: "/images/cover-retrait-impot.jpg",
    alt: "Enveloppe cachetée et pièces d’argent : impôt au retrait du 3a.",
    width: 1152,
    height: 864,
  },
  serieMontants: {
    src: "/images/cover-serie-montants.jpg",
    alt: "Piles de pièces en progression et montre de gousset : série des plafonds 3a.",
    width: 1152,
    height: 864,
  },
  roleLpp: {
    src: "/images/cover-role-lpp.jpg",
    alt: "Canne, alliance et olivier : retraite, survivants et invalidité du 2e pilier.",
    width: 1152,
    height: 864,
  },
  ouvrirFrontalier: {
    src: "/images/cover-ouvrir-frontalier.jpg",
    alt: "Écharpe marine et café à l’aube : ouvrir un 3a quand on est frontalier.",
    width: 1152,
    height: 864,
  },
  commencer: {
    src: "/images/cover-commencer.jpg",
    alt: "Bouture de romarin et enveloppe cachetée : commencer son 3e pilier.",
    width: 1152,
    height: 864,
  },
  tirelire: {
    src: "/images/cover-tirelire.jpg",
    alt: "Tirelire de céramique et crayons : constituer une épargne enfant.",
    width: 1152,
    height: 864,
  },
  beneficiaires: {
    src: "/images/cover-beneficiaires.jpg",
    alt: "Trois tasses de porcelaine, l’une vide : bénéficiaires du 3e pilier.",
    width: 1152,
    height: 864,
  },
  geneveImpot: {
    src: "/images/cover-geneve-impot.jpg",
    alt: "Arcade de la vieille ville de Genève et dossier crème : impôt cantonal et 3a.",
    width: 1152,
    height: 864,
  },
  transfertLpp: {
    src: "/images/cover-transfert-lpp.jpg",
    alt: "Grand dossier et petite enveloppe : transfert d’un avoir LPP vers le 3a.",
    width: 1152,
    height: 864,
  },
  retraitCompare: {
    src: "/images/cover-retrait-compare.jpg",
    alt: "Cadenas ouvert et ruban de soie : retirer un 3a ou un 3b.",
    width: 1152,
    height: 864,
  },
  support: {
    src: "/images/cover-support.jpg",
    alt: "Boîte de pierre et boîte de cuir : choisir le support d’un 3a.",
    width: 1152,
    height: 864,
  },
  rachat2e: {
    src: "/images/cover-rachat-2e.jpg",
    alt: "Balance de céramique, pièces et pierre : financer un rachat LPP avec le 3a.",
    width: 1152,
    height: 864,
  },
  source: {
    src: "/images/cover-source.jpg",
    alt: "Feuille vierge et crayon rouge : impôt à la source et 3a.",
    width: 1152,
    height: 864,
  },
  avsFrontalier: {
    src: "/images/cover-avs-frontalier.jpg",
    alt: "Café et carte vierge sur une tablette de train : AVS suisse du frontalier.",
    width: 1152,
    height: 864,
  },
  deductionSource: {
    src: "/images/cover-deduction-source.jpg",
    alt: "Enveloppe crème, balance de laiton et dossier vert sur chêne : déduction du 3e pilier à l’impôt à la source.",
    width: 1152,
    height: 864,
  },
  fraisAssurance: {
    src: "/images/frais-assurance-vie.jpg",
    alt: "Heurtoir de laiton sur un portail vert sombre.",
    width: 1152,
    height: 864,
  },
} as const satisfies Record<string, SiteImage>;

const SLUG_COVER: Record<string, keyof typeof IMAGES> = {
  "3eme-pilier-suisse": "mixte",
  "exemple-de-comparatif": "papier",
  "3eme-pilier-a-ou-b": "mixte",
  "3eme-pilier-b-prevoyance-libre": "pillar3b",
  "3eme-pilier-banque-assurance": "banque",
  "3eme-pilier-mixte": "mixteContrat",
  "choisir-son-3eme-pilier": "alpes",
  "deductions-fiscales-3eme-pilier": "deductions",
  "frontalier-suisse": "frontalier",
  "3eme-pilier-independant": "independant",
  "3eme-pilier-geneve": "geneve",
  "assurance-vie-en-suisse": "assurance",
  "frais-assurance-vie-3e-pilier": "fraisAssurance",
  "assurance-deces": "laiton",
  "risque-pur-deces": "risque",
  "epargne-enfant": "enfant",
  "analyse-de-prevoyance": "conseiller",
  "liberation-du-paiement-des-primes": "liberation",
  "1er-pilier-avs-ai-apg": "renteAvs",
  "2eme-pilier-lpp": "lpp",
  "libre-passage-lpp": "passage",
  "compte-de-libre-passage-lpp": "compteLp",
  "formulaire-3eme-pilier": "hero",
  "nous-contacter": "contact",
  "page-de-confidentialitee": "confidentialite",
  "page-remerciement": "merci",
  "declaration-impot-gratuite": "declaration",
  "actualite-3eme-pilier": "lavaux",
  "mentions-legales": "mentions",
  "a-propos": "apropos",
  "choisir-entre-3eme-pilier-bancaire-ou-en-assurance": "arbitrage",
  "taxation-ordinaire-ulterieure": "tou",
  "3eme-pilier-a-impot-retrait": "retraitImpot",
  "quel-montant-deductible-3eme-pilier-2022": "serieMontants",
  "a-quoi-sert-le-deuxieme-pilier": "roleLpp",
  "ouvrir-un-3eme-pilier-pour-un-frontalier": "ouvrirFrontalier",
  "quand-commencer-le-3eme-pilier": "commencer",
  "pourquoi-souscrire-au-3eme-pilier": "couple",
  "constituer-une-epargne-enfant": "tirelire",
  "choisir-les-beneficiaires": "beneficiaires",
  "plafonds-3a-2026-2027": "plafonds",
  "rachat-lacunes-3a-2026": "tirelire",
  "tableau-ofas-montants-avs-lpp-3a": "avs",
  "3a-impot-cantonal-geneve-2026": "geneveImpot",
  "3b-deduction-fribourg": "fribourg",
  "3eme-pilier-canton-vaud": "vaud",
  "frontalier-avs-3a-conditions": "avsFrontalier",
  "tou-impot-source-3a": "source",
  "deduction-3e-pilier-impot-a-la-source": "deductionSource",
  "depart-suisse-retrait-3a": "depart",
  "combiner-3a-et-3b-2026": "combiner",
  "frais-3a-banque-assurance": "frais",
  "methode-sources-ofas-afc": "papier",
  "versement-3a-avant-31-decembre-2026": "decembre",
  "retraite-avs-21-femmes-3a": "cliente",
  "choisir-support-3a-2026": "support",
  "retrait-3a-vs-3b-2026": "retraitCompare",
  "rachat-2e-pilier-avec-3a": "rachat2e",
  "rachat-lpp-vers-3a-2026": "transfertLpp",
};

export function coverFor(slug: string, cover?: string): SiteImage {
  if (cover && cover in IMAGES) {
    return IMAGES[cover as keyof typeof IMAGES];
  }
  const key = SLUG_COVER[slug] ?? "hero";
  return IMAGES[key];
}
