import { chf, FIGURES, YEARS } from "@/lib/figures";
import { AUTHOR } from "@/lib/editorial";
import { SITE as SITE_PUBLIC } from "@/lib/site";
import {
  FORM,
  HUB,
  PENDING,
  REVIEW,
  TODO_AFA,
  TODO_ADDRESS,
  TODO_ENTITY,
  TODO_PAY,
  TODO_REGISTER,
  TODO_STATUS,
  TODO_UID,
  type EnCopy,
  grand,
  h2,
  ol,
  p,
  petit,
  ul,
} from "./shared";

const mail = SITE_PUBLIC.email;

export const EN_B: Record<string, EnCopy> = {
  "3eme-pilier-mixte": {
    title: "Endowment-style third pillar",
    metaTitle: "Mixed third pillar: savings and risk in one policy",
    description: "One policy can mix savings and a death benefit. Neither capital is published here.",
    intro: "A so-called mixed policy pays a capital if you are alive at the end, and a capital if you die before. The two amounts are not always equal. It is not a mandatory form of pillar 3a, and this page does not state a capital in advance. You pay savings and risk in the same premium.",
    brief: ["One contract mixes both costs.", "If the death need is high and savings are small, a pure risk policy plus a bank 3a is often easier to read.", "No return is announced here.", PENDING],
    faqs: [
      { question: "Is a mixed third pillar mandatory?", answer: "No. A pillar 3a can be a bank foundation, with no built-in death capital." },
      { question: "Is the mixed capital guaranteed?", answer: "Not on this page. Some contracts state a capital, others link it to funds. The figure is on the offer, with the surrender table." },
    ],
    blocks: [h2("What to have in front of you"), ul(["Capital if you are alive at the end, and capital at death.", "Surrender value year by year.", "What happens if you stop the premiums."]), p(HUB)],
  },
  "choisir-son-3eme-pilier": {
    title: "How to choose a third pillar",
    metaTitle: "Choosing a third pillar in 2026: a method, not a ranking",
    description: "Questions before the product: ceiling, horizon, protection, canton. No ranking.",
    intro: "Choosing a third pillar is not the best rate of the moment. It is lining up the 2026 tax ceiling, a time horizon, a need for protection, and a support you will actually keep. Pillar 3a and pillar 3b do not replace each other. Neither do bank and insurance.",
    brief: [`2026 ceiling: ${petit} with a 2nd pillar, or 20% of income up to ${grand} without.`, "No return, no sample capital and no provider ranking is published here.", "The comparison is free. You do not have to take a contract.", PENDING],
    faqs: [
      { question: "Must I reach the pillar 3a ceiling?", answer: `No. ${petit} or ${grand} is a 2026 maximum deduction, not a target.` },
      { question: "Does the site name the best contract?", answer: "No. There is no ranking. No diploma and no register is displayed: they are not established here." },
    ],
    blocks: [h2("Five questions before the product"), ol(["What gap is there between OASI/BVG pensions and the retirement budget?", "Can you aim at the pillar 3a ceiling without emptying your cash reserve?", "Do you need a death capital or a waiver of premium, or only savings?", "Is the horizon under about eight years, or until reference age?", "Canton and status change the tax result."]), p(HUB), p(FORM)],
  },
  "frontalier-suisse": {
    title: "Third pillar for a cross-border worker",
    metaTitle: "Cross-border third pillar: OASI, withholding tax, leaving Switzerland",
    description: "A cross-border worker can open a pillar 3a if Swiss earned income is subject to OASI.",
    intro: "Can a cross-border worker open a pillar 3a? Yes, if earned income in Switzerland is subject to OASI. The G permit does not open the right. OASI liability does (FSIO, FTA circular no. 18). The tax interest then depends on the source, a possible subsequent ordinary assessment, and the law of the state of residence.",
    brief: [`2026 ceiling: ${petit} with a 2nd pillar, or 20% up to ${grand} without.`, "The deduction becomes concrete mainly if a subsequent ordinary assessment applies.", "Buying a home outside Switzerland is not the Swiss owner-occupied withdrawal reason.", PENDING],
    faqs: [
      { question: "What if I leave Switzerland?", answer: "A definitive departure is a reason for early payment of pillar 3a (FSIO). Rules differ if you stay in the EU/EFTA or not, and they differ for the 2nd pillar." },
      { question: "Does the 3a deduction show up in withholding tax?", answer: "Not in the withholding scale. It becomes concrete mainly if a subsequent ordinary assessment applies." },
    ],
    blocks: [p("Detail: [OASI conditions](/en/frontalier-avs-3a-conditions/), [withholding tax and pillar 3a](/en/tou-impot-source-3a/), [leaving Switzerland](/en/depart-suisse-retrait-3a/)."), p(HUB)],
  },
  "3eme-pilier-geneve": {
    title: "Third pillar in Geneva",
    metaTitle: "Geneva third pillar: the federal ceiling, plus life premiums",
    description: "Geneva does not raise the pillar 3a ceiling. The cantonal rule targets life-insurance premiums.",
    intro: `Is the pillar 3a ceiling higher in Geneva? No. In 2026 it is the federal FSIO maximum: ${petit} with a 2nd pillar, ${grand} without. Cantonal income tax changes the saving, not the right to pay in. The Geneva rule targets life-insurance premiums, not a 3b bonus. ${PENDING}.`,
    brief: ["Same federal 3a ceiling as the rest of Switzerland.", "Article 31(d) of the Geneva tax act targets life premiums and savings interest.", "Check the year’s cantonal notice. Figures can be adjusted.", PENDING],
    faqs: [
      { question: "Is there a Geneva bonus on pillar 3a?", answer: "No. The right to pay in is the federal ceiling. The cantonal tax changes the francs saved, not that ceiling." },
      { question: "What about life premiums?", answer: `Article 31(d) targets life-insurance premiums. Orders of magnitude often cited: about ${chf(FIGURES.ge3bSingle)} for a single person, ${chf(FIGURES.ge3bMarried)} for spouses, ${chf(FIGURES.ge3bPerChild)} per dependant. That is the year’s Geneva notice, not OPP 3.` },
    ],
    blocks: [p(HUB)],
  },
  "assurance-vie-en-suisse": {
    title: "Life insurance in Switzerland",
    metaTitle: "Life insurance in Switzerland: risk, endowment, 3a and 3b",
    description: "Four readings: pure risk, endowment, pillar 3a and pillar 3b. No guaranteed capital is announced.",
    intro: "Life insurance in Switzerland is not one product. A pure risk pays if death occurs during the term and builds no savings. An endowment mixes savings and death. A pillar 3a policy is tied and deductible inside the FSIO ceiling. A pillar 3b policy is flexible. This page announces no guaranteed capital.",
    brief: ["Read the surrender table before you sign.", "The federal deduction belongs to pillar 3a, not to the word insurance.", "No ranking of insurers.", PENDING],
    faqs: [{ question: "Does life insurance raise the 3a ceiling?", answer: `No. The 2026 ceiling stays ${petit} or ${grand}, provider aside.` }],
    blocks: [p("Related: [pure death risk](/en/risque-pur-deces/), [death cover](/en/assurance-deces/), [bank or insurance](/en/3eme-pilier-banque-assurance/). The fee lines of a policy are on [life-insurance fees in pillar 3](/en/frais-assurance-vie-3e-pilier/)."), p(HUB)],
  },
  "frais-assurance-vie-3e-pilier": {
    title: "Life insurance fees in pillar 3: premium, management, surrender",
    metaTitle: "Life insurance fees in pillar 3: premium, management, surrender",
    description: "Premium, entry costs, management costs and surrender costs of a life policy in the Swiss third pillar. Pure risk or endowment, 3a or 3b. No fee average.",
    intro: "The premium of a life policy in the Swiss third pillar is not one price. It pays for cover, sometimes savings, and costs. Compare the premium, entry costs, management costs and surrender costs. A pure risk and an endowment do not split those francs the same way. A recognised pillar 3a changes the deduction and the exits. Pillar 3b has no equivalent general federal deduction.",
    brief: [
      "Read the premium in francs, then split it: risk, savings if any, costs.",
      "Entry costs weigh at the start. The early surrender values show it.",
      "Management costs are on the policy and, if there are funds, on the support.",
      "Surrender is the table in the contract, not the sum of premiums.",
      "The deduction exists only for a recognised pillar 3a, inside the legal limits. No general federal deduction in pillar 3b.",
    ],
    faqs: [
      { question: "Is the premium a fee?", answer: "No. The premium is the payment. Costs are one part of it, with the risk and, in an endowment, the savings. Split the amount. Do not compare it alone." },
      { question: "Why is the surrender value often low at the start?", answer: "Entry costs and the cost of risk are usually taken early. The surrender value does not add up the premiums. The figure is on the contract table. No market percentage replaces it." },
      { question: "Does a pure risk have surrender costs?", answer: "Usually there is no surrender value, or it is negligible. The premium paid for death cover during the term. Compare the capital, the term and the exclusions." },
      { question: "Does a pillar 3a policy deduct more than a pillar 3a account?", answer: "No. Only a recognised pillar 3a fits the legal limits. The ceiling is the same at a bank and at an insurer. The policy does not create an extra deduction." },
      { question: "Is pillar 3b deductible like pillar 3a?", answer: "Not for federal direct tax: there is no equivalent general federal deduction. A cantonal deduction of life premiums, when it exists, follows that canton and the year’s notice. It is not the federal ceiling." },
      { question: "Where do you read the costs without an average percentage?", answer: "On the offer: premium, entry or acquisition costs, management costs, surrender table. If there are funds, the support’s cost line. A comparison puts those documents side by side." },
    ],
    blocks: [
      h2("What the premium pays"),
      p("The premium is what you pay, usually each month or each year. It is the envelope, not a fee by itself. The contract splits risk, savings when they exist, and policy costs. Two equal premiums can leave very different savings. On an endowment, one part feeds a capital or a fund, another pays for death during the term, another covers costs. A waiver of premium or a disability pension, if the contract includes them, also has a cost. On a [pure risk](/en/risque-pur-deces/), the premium pays for the cover and its costs. It does not build savings like an account. This page publishes no average fee."),
      h2("Entry costs"),
      p("Entry costs, often called acquisition or conclusion costs, pay for setting up the contract. They are usually taken at the start, sometimes spread over the first years, sometimes so embedded that no line isolates them. You then see them in the effect: a surrender value of nothing, or far below the premiums already paid. No typical percentage applies to every policy. Ask for the surrender table of the first years, and for the line that names these costs. The same reading is on [surrender value](/en/valeur-de-rachat-3a/)."),
      h2("Management costs"),
      p("Management costs pay for running the contract. Depending on the policy, they apply to the premium, the savings, or the value of a support. When the contract is linked to funds, the support has its own costs, on top of the policy’s. Read both. Check the base, the frequency, and whether the amount is a franc fee or a share of the value. No average rate is given here."),
      h2("Surrender costs"),
      p("Surrender here means ending the insurance contract before the term and receiving the surrender value. It is not a pillar 3a contribution buy-back, which fills unpaid years inside the legal limits. The surrender cost, or the reduction it produces, shows in the amount the policy pays on the way out, year by year. That value is not the sum of premiums, not the maturity capital, and not the death capital. In the first years it is often lower than the premiums already paid, because entry costs and the cost of risk were taken first. The only reliable figure is the table. This page invents none. If premiums stop, the outcomes are those of the contract: [stopping a pillar 3a policy](/en/arret-primes-assurance-3a/)."),
      p("A pure risk usually has no surrender value: the premium paid for a risk, not for savings you get back. An [endowment](/en/3eme-pilier-mixte/) has one, according to the contract. In pillar 3a you cannot cash it freely: you need a reason set by the rules, or a transfer that stays tied pension. In pillar 3b, surrender follows the policy, outside those reasons, but the costs remain."),
      h2("Pure risk and endowment"),
      p("A [pure risk](/en/risque-pur-deces/) and an [endowment](/en/3eme-pilier-mixte/) do not carry the same cost lines. On a pure risk, the premium serves death during a term. There is no savings pot, so no management cost on built-up capital, and in principle nothing to surrender. Compare the capital, the term and the exclusions. Do not compare that premium with a payment into an account. On an endowment, the same premium mixes savings and death. Entry costs weigh at the start, management costs touch the savings part, and the surrender value matters if the horizon may shorten. An endowment premium of the same amount as a [bank](/en/3eme-pilier-banque-assurance/) payment does not leave the same savings: part of it pays for risk and costs. [Life insurance in Switzerland](/en/assurance-vie-en-suisse/) sets these forms side by side. No return is announced here."),
      h2("What pillar 3a changes compared with pillar 3b"),
      p("The same cost lines exist in both frames. What changes is the deduction, the lock-in, and the use of the surrender value. The split is on [pillar 3a or 3b](/en/3eme-pilier-a-ou-b/)."),
      p(`A pillar 3a is deductible only if it is recognised tied pension, and only inside the legal limits. In 2026, article 7 and the FSIO table of 1 January set ${petit} with a 2nd-pillar institution, and 20% of earned income up to ${grand} without one. Federal direct tax follows that deduction. A policy does not create a higher ceiling than a bank foundation.`),
      p(`From 1 January 2027 the Federal Council sets those ceilings at ${chf(YEARS[2027].pillar3aWithLpp)} with a 2nd pillar and ${chf(YEARS[2027].pillar3aWithoutLpp)} at most without one. The 20% rate is unchanged. Those amounts do not apply to a payment credited in 2026.`),
      p("In pillar 3a the exit is tied. You do not surrender the policy like a free investment: you need a reason the rules provide, or a transfer that stays tied pension. What moves is the contract value on that date, not the sum of premiums. Pillar 3b is flexible provision. It does not open a general federal deduction equivalent to pillar 3a. Federal direct tax does not treat a pillar 3b premium like the tied contribution. A canton may allow life-insurance premiums under its own rules, often inside an envelope already used by other premiums. That is not a second federal ceiling, and it is not automatic: the year’s tax notice says so. Surrender follows the policy. Costs do not vanish because the frame is flexible."),
      h2("What to have in front of you"),
      p("A cost comparison does not rank insurers. It lines up the annual premium, the surrender table, the maturity and death capitals, entry and management costs, what happens if premiums stop, and whether the frame is pillar 3a or 3b. Without those lines, a low premium says nothing."),
      p(FORM),
    ],
  },
  "analyse-de-prevoyance": {
    title: "A pension review before the product",
    metaTitle: "Pension review: OASI, BVG, existing 3a, then the support",
    description: "Order of reading: OASI, occupational pension, 3a already open, death need, then the support.",
    intro: "A pension review starts with the pensions you already have, not with a product name. OASI, the occupational pension, pillar 3a contracts already open, then the death need, and only then bank or insurance. This page publishes no sample gap in francs.",
    brief: ["Existing contracts first.", "No diploma or register is displayed.", "The comparison does not commit you.", PENDING],
    faqs: [{ question: "Does the review name a winner?", answer: "No. It lines up the documents. The choice stays yours." }],
    blocks: [p(HUB), p(FORM)],
  },
  "libre-passage-lpp": {
    title: "Vested benefits are not a pillar 3a",
    metaTitle: "Vested benefits account: not a third pillar",
    description: "A vested-benefits account holds 2nd-pillar money when you leave a pension fund. It is not a pillar 3a.",
    intro: "Vested benefits hold occupational-pension assets when you leave a pension fund and do not move them straight into a new one. That is 2nd-pillar money. It is not a pillar 3a, and it does not use the 3a deduction. The deadline before a substitute institution may have to take the assets is not numbered on this page.",
    brief: ["2nd pillar, not 3a.", "A direct transfer from vested benefits into a 3a is not described as possible here.", PENDING],
    faqs: [{ question: "Can I move vested benefits into a pillar 3a?", answer: "Not by a direct transfer. The movement the law describes the other way, in some buy-back cases, is 3a toward the pension fund." }],
    blocks: [p("See [using a 3a to fund a pension-fund buy-back](/en/rachat-2e-pilier-avec-3a/) and the [2nd pillar](/en/2eme-pilier-lpp/)."), p(HUB)],
  },
  "compte-de-libre-passage-lpp": {
    title: "Vested-benefits account",
    metaTitle: "Vested-benefits account under the occupational pension",
    description: "Where 2nd-pillar assets sit between two employers. Not a pillar 3a ceiling.",
    intro: "A vested-benefits account or policy keeps occupational-pension assets between two jobs, or when you leave Switzerland’s pension system. It is not a third pillar and it does not follow the pillar 3a ceiling.",
    brief: ["It preserves 2nd-pillar money.", "It is not an extra 3a deduction."],
    blocks: [p("The longer note is [vested benefits](/en/libre-passage-lpp/)."), p(HUB)],
  },
  "formulaire-3eme-pilier": {
    title: "Request a comparison",
    metaTitle: "Comparison form — the form itself is in French",
    description: "The comparison form is in French because the field labels are French. It is free and does not commit you.",
    intro: "This English page does not translate the form. The labels, the canton list and the situation list are French, and the submission path stays that French form. Sending it is free and does not commit you. No diploma or register is displayed, because those facts are not established.",
    brief: ["Fields: first name, last name, email, phone, canton, situation, an optional note, and consent.", "A service adviser calls back if the file is passed on.", "You do not have to take a contract."],
    blocks: [p(FORM), p(HUB)],
  },
  "nous-contacter": {
    title: "Contact",
    metaTitle: "Contact the comparison service",
    description: "Write to the service. The contact form stays in French. Email is also open.",
    intro: `To contact the service, use the French contact form or write to ${mail}. The form asks for a name, email, phone and your question. There is no automatic confirmation email.`,
    brief: ["The form is in French.", `Email: ${mail}.`, "A person calls back if the file is passed on."],
    blocks: [p("Open the [French contact form](/nous-contacter/)."), p(HUB)],
  },
  "page-de-confidentialitee": {
    title: "Privacy notice",
    metaTitle: "Privacy — comparateur-3eme-pilier.ch",
    description: "What the forms collect, why, and which rights the Swiss Data Protection Act gives you. The historical URL is kept.",
    intro: "This page stays on the historical URL /page-de-confidentialitee/. The corrected spelling redirects here. Only the processing described below is stated.",
    blocks: [
      h2("1. Controller"),
      p(`comparateur-3eme-pilier.ch collects contact data when you use the forms. Contact: ${mail}.`),
      h2("2. Data collected"),
      p("Identity, email, phone, canton, work situation, pension details you type, message, date and time, and minimal technical logs such as an IP address. There is no card field."),
      h2("3. Purposes"),
      ul(["Answer a contact or comparison request.", "Pass the file to a partner adviser to prepare offers. Not a sale of the file.", "Keep proof of consent and a lead journal.", "Improve the site if an audience tool is later switched on."]),
      h2("4. Legal basis"),
      p("The Federal Act on Data Protection. Processing serves your request and the running of the service. Consent is asked before the file goes to a partner. You refuse it by not sending the form."),
      h2("5. Recipients"),
      p("The site team, the host, and the partner who prepares the comparison. Data is not resold. The user is not charged a fee for the offers."),
      h2("6. Retention"),
      p("Requests are kept for the handling, then archived in a limited way for accounting and proof. Pieces with a legal reach can be kept up to 10 years in practice. Otherwise they are deleted sooner."),
      h2("7. Rights"),
      p(`Access, correction, deletion, surrender, objection. Write to ${mail}. Authority: the Federal Data Protection and Information Commissioner.`),
      h2("8. Cookies"),
      p("This rebuilt site does not embed Google Analytics or a tag manager by default. Strictly necessary session cookies may be set. If an audience tool is added later, this page will be updated."),
      h2("9. Security"),
      p("HTTPS, restricted access to lead logs, and an anti-bot field. No security is absolute."),
    ],
  },
  "page-remerciement": {
    title: "Request received",
    metaTitle: "Your request — Comparateur 3ème pilier",
    description: "After the French form, a person calls back within two business days if the file was passed on.",
    intro: "The form submits in French and lands on the French confirmation URL. If the file reached the internal follow-up, an adviser calls back within two business days, preferably by phone. No confirmation email is promised.",
    blocks: [p(`If you hear nothing within two business days, write to ${mail} and mention your phone number.`)],
  },
  "declaration-impot-gratuite": {
    title: "The 2022 free tax-return offer has ended",
    metaTitle: "Tax return — the 2022 offer has expired",
    description: "The old “2022 tax return included” promotion is no longer sold. The third-pillar comparison stays free.",
    intro: "This URL existed for a 2021–2022 promotion that offered a tax return to new clients. It is no longer sold. The slug is kept so old links do not break.",
    blocks: [p("The third-pillar comparison stays free and without commitment. For a tax return, use a fiduciary or the cantonal office. This site does not replace a fiduciary.")],
  },
  "actualite-3eme-pilier": {
    title: "Third-pillar guides",
    metaTitle: "Third-pillar guides — three articles a week",
    description: "Editorial series: three pieces a week on FSIO ceilings, cantons, cross-border workers, 3a and 3b. Historical guides keep their URLs.",
    intro: "Three texts a week, not an article a day. The guides already online keep their original URLs. English versions use the same slug under /en/.",
    blocks: [p(HUB)],
  },
  "exemple-de-comparatif": {
    title: "A sample comparison",
    metaTitle: "Sample comparison",
    description: "A teaching example. No provider, no offer and no performance is named.",
    intro: "This is a teaching fiction. It shows the shape of a comparison: fees, flexibility, surrender value, guarantees and horizon. It does not name a bank, an insurer, a return or a winner.",
    brief: ["Every figure that is not an official 2026 ceiling is labelled hypothetical.", "No partner is named.", "The market is not claimed to be exhaustive."],
    faqs: [{ question: "Is this someone’s real offer?", answer: "No. It is a pedagogical example. A real comparison starts from your documents, not from this page." }],
    blocks: [p(`Official 2026 ceiling, for scale only: ${petit} with a 2nd pillar. ${PENDING}.`), p(HUB)],
  },
  "1er-pilier-avs-ai-apg": {
    title: "1st pillar: OASI, disability insurance and income compensation",
    metaTitle: "OASI pensions in 2026",
    description: "2026 OASI pension range from the FSIO table, the 13th pension from December 2026, and the link to the third pillar.",
    intro: `The 1st pillar is the basic pension: OASI for old age and survivors, disability insurance, and income-compensation allowances. In 2026 a full old-age pension runs from ${chf(FIGURES.avsMinMonthly)} to ${chf(FIGURES.avsMaxMonthly)} a month. For a married couple the cap on the two pensions is ${chf(FIGURES.avsCoupleMaxMonthly)}. ${PENDING}. That pension does not usually replace a salary. That is why the 2nd and 3rd pillars exist.`,
    brief: ["Figures from the FSIO table of 1 January 2026.", "The 13th OASI pension is an OASI benefit, not a higher 3a ceiling.", PENDING],
    faqs: [
      { question: "Does the 13th pension change the 3a ceiling?", answer: `No. The 13th pension is an OASI benefit. The 2026 pillar 3a ceiling stays ${petit} or ${grand}. ${PENDING}.` },
      { question: "Are 2027 OASI pensions published?", answer: `This page keeps the 1 January 2026 OASI table and does not restate other 2027 OASI amounts. ${PENDING}.` },
    ],
    blocks: [p(HUB)],
  },
  "2eme-pilier-lpp": {
    title: "2nd pillar, BVG/LPP",
    metaTitle: "BVG/LPP thresholds in 2026",
    description: "2026 entry threshold, coordination deduction and upper limit, and why affiliation changes the 3a ceiling.",
    intro: `The 2nd pillar is the occupational pension. Employer and employee fund a scheme that pays a pension or a capital. In 2026 compulsory affiliation starts at ${chf(FIGURES.lppEntry)} of annual salary with the same employer. The coordination deduction is ${chf(FIGURES.lppCoordination)}, the upper limit ${chf(FIGURES.lppSalaryCap)}. Being affiliated or not also decides whether your pillar 3a is capped at ${petit} or at 20% of income. ${PENDING}.`,
    brief: ["Thresholds from the FSIO table of 1 January 2026.", "Affiliation changes the 3a ceiling. It does not by itself forbid a 3a.", PENDING],
    faqs: [{ question: "Are the 2027 BVG thresholds published?", answer: `This page keeps the 1 January 2026 BVG table and does not restate other 2027 BVG thresholds. ${PENDING}.` }],
    blocks: [p(HUB)],
  },
  "epargne-enfant": {
    title: "Saving for a child",
    metaTitle: "Saving for a child: pillar 3b, not a child’s 3a",
    description: "A child with no OASI income does not open a pillar 3a. Flexible pillar 3b is the route the site describes.",
    intro: "A child with no income subject to OASI does not open a pillar 3a. The parent who does have OASI income can use their own 3a, inside their own ceiling. Money set aside in the child’s name is generally flexible pillar 3b, with the contract’s access and beneficiary rules.",
    brief: ["No OASI income, no pillar 3a.", "The parent’s 3a ceiling is not increased by the child.", "Read who owns the contract and who the beneficiary is."],
    faqs: [{ question: "Can I deduct a 3a in my child’s name?", answer: "Not if the child has no income subject to OASI. The deduction follows the person who has that income." }],
    blocks: [p(HUB)],
  },
  "assurance-deces": {
    title: "Death cover",
    metaTitle: "Death cover beside a third pillar",
    description: "A death benefit is a contract clause, not an automatic feature of every pillar 3a.",
    intro: "Death cover pays a capital to beneficiaries. A bank 3a pays the balance that exists. An insurance policy pays what the contract states, which can differ from the premiums paid and from the surrender value. This page publishes no sample capital.",
    brief: ["Read the beneficiary clause.", "A partner of four years is not automatically in the spouse’s rank on a 3a.", "No return is added."],
    faqs: [{ question: "Is every 3a a death insurance?", answer: "No. A bank account pays the assets. Death capital beyond that is a policy clause." }],
    blocks: [p("Beneficiaries: [who receives a 3a](/en/choisir-les-beneficiaires/). Pure term cover: [pure risk](/en/risque-pur-deces/)."), p(HUB)],
  },
  "risque-pur-deces": {
    title: "Pure death risk",
    metaTitle: "Term life cover without savings",
    description: "Pure risk pays if death occurs during the term. It does not build a surrender value like an endowment.",
    intro: "A pure death-risk policy pays if death occurs during the term. It does not build savings. The premium is the price of the cover. It is often easier to read beside a bank pillar 3a than inside one mixed premium.",
    brief: ["No savings capital at the end.", "The 3a deduction is a separate decision.", "No sample premium is published."],
    faqs: [{ question: "Is pure risk a pillar 3a?", answer: "Not by itself. It can sit next to a 3a. It does not replace the FSIO ceiling." }],
    blocks: [p(HUB)],
  },
  "liberation-du-paiement-des-primes": {
    title: "Waiver of premium",
    metaTitle: "Waiver of premium: disability cover, not a pause",
    description: "Waiver of premium keeps a policy funded if you cannot pay because of disability. It is not a choice to stop.",
    intro: "Waiver of premium is a guarantee: if disability meets the contract, the insurer keeps paying the premiums. It is not a voluntary pause, and it does not replace OASI disability benefits or a 2nd-pillar disability pension.",
    brief: ["It has a price inside the premium.", "It applies only if the contract includes it.", "Stopping because you choose to is a different page."],
    faqs: [{ question: "Can I switch waiver of premium on when I want to stop?", answer: "No. It responds to incapacity defined in the contract, not to a decision to pause." }],
    blocks: [p("Choosing to stop: [stopping premiums](/en/arret-primes-assurance-3a/)."), p(HUB)],
  },
  "a-propos": {
    title: "About",
    metaTitle: "About the third-pillar comparison",
    description: "Who publishes the comparison, how figures are checked, and what the site does not do.",
    intro: `${AUTHOR.name} is head of content and of the comparison. The site explains the third pillar from FSIO and FTA texts and takes comparison requests. It does not rank products and does not promise a return.`,
    brief: ["General information for French-speaking Switzerland.", "Pillar 3a figures cited for 2026, FSIO source.", PENDING, "The comparison is presented as free and without commitment.", "No portrait and no diploma: they are not established here."],
    faqs: [
      { question: "Is this personal advice?", answer: "No. The pages describe general rules. A comparison requested through the form is a conversation about your situation, not an asset-management mandate signed on the site." },
      { question: "Where do the figures come from?", answer: `From the FSIO table of 1 January 2026 and article 7 OPP 3, checked on ${REVIEW}. ${PENDING}.` },
    ],
    blocks: [
      h2("Who runs the service"),
      p(`${AUTHOR.name} writes or has the pages checked, and handles comparison requests. Contact: ${mail}. The legal name, address and UID are not published until they are established. See the [legal notice](/en/mentions-legales/).`),
      h2("What is compared"),
      p("Solutions the service can actually access: fees, payment flexibility, surrender value, death or disability cover, horizon. The site does not claim to list every institution in Switzerland. The [comparison methodology](/en/methodologie-comparatif/) says what is read. The [source method](/en/methode-sources-ofas-afc/) says where the figures come from. The responsible person is [Christophe Bouin](/en/christophe-bouin/)."),
      ul(["Not a replacement for your fiduciary or your pension fund.", "No guaranteed return.", "No FINMA registration is displayed: none is documented.", TODO_PAY]),
    ],
  },
  "mentions-legales": {
    title: "Legal notice",
    metaTitle: "Legal notice — third-pillar comparison",
    description: "Publisher, contact and limits. Fields that are not established are marked as TODOs.",
    intro: "This notice describes comparateur-3eme-pilier.ch. Only facts already established are asserted. Address, UID and an intermediary status are not invented.",
    brief: ["Trading name: Comparateur 3ème pilier.", `Content owner: ${AUTHOR.name}.`, `Contact: ${mail}.`, "Comparison presented as free and without commitment.", "Legal name, address, UID and register: waiting for a human check."],
    blocks: [
      h2("Identification"),
      ul(["Trading name: Comparateur 3ème pilier.", TODO_ENTITY, TODO_ADDRESS, TODO_UID, `Head of content and of the comparison: ${AUTHOR.name}.`, `Contact: ${mail}.`]),
      h2("Status and register"),
      ul([TODO_STATUS, TODO_REGISTER, TODO_AFA]),
      h2("What the service is"),
      p("The site publishes general information on the third pillar and collects a comparison request. It is not personal investment advice concluded on this page. [About](/en/a-propos/)."),
      h2("Pay"),
      p(TODO_PAY),
    ],
  },
  "christophe-bouin": {
    title: "Christophe Bouin",
    metaTitle: "Christophe Bouin, head of content and of the comparison",
    description: "Name and role already established. Portrait, biography, years, qualifications and registrations are not.",
    label: "Author",
    intro: `${AUTHOR.name} is head of content and of the comparison. That is the only identity fact published. Contact: ${mail}. This page does not contain a biography, a portrait, years of experience or a qualification. Those items are not in the repository.`,
    brief: [`${AUTHOR.name}, head of content and of the comparison.`, `Contact: ${mail}.`, "Portrait, biography, experience, qualifications and registrations: not established.", "No diploma is displayed."],
    blocks: [
      h2("What is established"),
      ul([`Name: ${AUTHOR.name}.`, "Role: head of content and of the comparison.", `Contact: ${mail}.`, "Service page: [about](/en/a-propos/)."]),
      h2("What is not established"),
      p("The lines below are gaps, not titles. Nothing is invented to fill them."),
      ul(["Portrait: not established.", "Detailed biography: not established.", "Years of experience: not established.", "Qualifications: not established.", "Intermediary registration: not established.", TODO_STATUS, TODO_AFA]),
    ],
  },
  "methodologie-comparatif": {
    title: "Comparison methodology",
    metaTitle: "How the third-pillar comparison is read",
    description: "What the comparison looks at among accessible solutions. Not a claim that the whole market is covered.",
    intro: "The comparison reads a situation, then the solutions accessible to the service. It does not claim to cover every institution in Switzerland: that exhaustiveness is not established. It does not rank, it does not promise a return, and it does not name a winner between bank and insurance.",
    brief: ["Scope: solutions the service can access, not the whole market.", "Criteria: fees, flexibility, surrender value, guarantees, horizon.", "A return is guaranteed only if the contract says so.", "Partner pay is not documented.", "Official figures live on the source-method page."],
    faqs: [
      { question: "Does the comparison see every Swiss offer?", answer: "No. The repository says the adviser looks at solutions accessible to the service, not the whole market." },
      { question: "How is the service paid?", answer: TODO_PAY },
    ],
    blocks: [
      h2("What is read"),
      ul(["Fees, with no invented scale: they are on the offer documents.", "Payment flexibility: free payments, or premiums set in the contract.", "Surrender value if you stop, especially in the early years of a policy.", "Guarantees: death capital, disability, waiver of premium, only if the contract includes them.", "Horizon: short, or until reference age."]),
      h2("Guaranteed return and a hypothetical return"),
      p("A capital or a rate is guaranteed only if the contract says so, and the figure is the contract’s, not this page’s. A hypothetical return, a past performance or a “likely” rate is not used to conclude. The [ceiling calculator](/en/calculateur-plafond-3a/) at most divides the ceiling. It does not project a capital."),
      h2("Pay"),
      p(`${TODO_PAY} The comparison stays presented as free and without commitment.`),
      p(`Where the official figures come from: [FSIO and FTA source method](/en/methode-sources-ofas-afc/). ${HUB} Responsible person: [Christophe Bouin](/en/christophe-bouin/).`),
    ],
  },
  "methode-sources-ofas-afc": {
    title: "Source method: FSIO and FTA",
    metaTitle: "Editorial method: FSIO, FTA, no ranking",
    description: "Where the Swiss-franc figures on this site come from, and what is refused: a ranking, a promised return, or a 2027 figure that is not in the 2 October 2026 release.",
    intro: "Where do the figures come from? From the FSIO table of 1 January 2026, from article 7 OPP 3, from FTA circular no. 18, and from the year’s cantonal notice when pillar 3b is involved. Not from a ranking, and not from an invented rise.",
    brief: ["Every pillar 3a franc amount should trace to the FSIO or to OPP 3.", "Cantonal 3b figures follow the year’s notice.", PENDING],
    faqs: [
      { question: "Who writes these articles?", answer: "The editorial team of the comparison service. A service adviser calls back to read offers. No diploma or register is displayed, because those facts are not established. The comparison stays free and without commitment." },
      { question: "When will the 2027 ceiling be updated?", answer: `They were set by the Federal Council on 2 October 2026. ${PENDING}. A 2026 payment still uses the 2026 ceilings.` },
    ],
    blocks: [
      p("What is compared — fees, flexibility, guarantees, limits — is on the [comparison methodology](/en/methodologie-comparatif/). This page does not repeat that grid."),
      ul([
        "[The third pillar, FSIO](https://www.bsv.admin.ch/fr/le-troisieme-pilier)",
        "[Amounts at 1 January 2026, FSIO](https://www.bsv.admin.ch/dam/fr/sd-web/sAgdISSXenMT/f_Betr%C3%A4ge%202026.pdf)",
        "[Your third-pillar contribution, FSIO](https://www.bsv.admin.ch/fr/votre-cotisation-au-3e-pilier)",
      ]),
      p(HUB),
    ],
  },
  "plafonds-3a-2026-2027": {
    title: "Pillar 3a ceilings",
    metaTitle: "Pillar 3a ceilings for 2026",
    description: "2026 ceilings from the FSIO table. The following year is not numbered.",
    intro: `Pillar 3a ceilings are not negotiated with a broker. For 2026 they are in the FSIO table of amounts at 1 January: ${petit} with a 2nd pillar, ${grand} at most without one. ${PENDING}.`,
    brief: ["With a pension fund: the small contribution.", "Without: 20% of earned income, inside the large contribution.", "Checked against the FSIO PDF.", PENDING],
    faqs: [
      { question: "Will you print a 2027 franc amount?", answer: `Yes. ${PENDING}. A 2026 payment still uses the 2026 ceilings.` },
    ],
    blocks: [p(`Historical ceilings for 2023–2024 and until 2022 are older FSIO figures. They are not the current right. The calculator: [2026 ceiling](/en/calculateur-plafond-3a/). ${HUB}`)],
  },
  "3eme-pilier-independant": {
    title: "Third pillar for a self-employed person",
    metaTitle: "Self-employed pillar 3a: the pension fund decides the ceiling",
    description: "Self-employed does not automatically mean the large contribution. Affiliation to a 2nd pillar does.",
    intro: `The word “self-employed” does not set the pillar 3a contribution. The test is affiliation to a 2nd-pillar institution. Without BVG/LPP: 20% of earned income, at most ${grand}. With a pension fund, including voluntary affiliation: ${petit}. Not every self-employed person has the large contribution.`,
    brief: ["OASI income is still required.", "Voluntary affiliation switches you to the small contribution.", "A gap buy-back stays capped at the small contribution.", PENDING],
    faqs: [{ question: "Do I get the large contribution because I am self-employed?", answer: "Only if you are not affiliated to a 2nd-pillar institution. Affiliation, even voluntary, uses the small contribution." }],
    blocks: [p(HUB)],
  },
  "choisir-entre-3eme-pilier-bancaire-ou-en-assurance": {
    title: "Bank or insurance: the same tax, a different exit",
    metaTitle: "Bank or insurance for pillar 3a",
    description: "Same 2026 deduction. What remains if you stop, and what is paid if you die, is what differs.",
    intro: "A pillar 3a is taken with a bank foundation or an insurer. The 2026 deduction does not change. What changes is what remains if you stop, and what is paid if you die.",
    brief: ["Short horizon and uneven savings: often a bank.", "Death cover and a premium discipline: often insurance, if you will keep it.", "No winner is named."],
    faqs: [{ question: "Is the deduction higher with insurance?", answer: `No. In 2026 the FSIO ceiling is ${petit} / ${grand}.` }],
    blocks: [p(HUB)],
  },
  "taxation-ordinaire-ulterieure": {
    title: "Subsequent ordinary assessment",
    metaTitle: "Subsequent ordinary assessment and pillar 3a",
    description: "Withholding tax does not show the 3a deduction. A subsequent ordinary assessment can.",
    intro: "A subsequent ordinary assessment is the procedure that can pull a person taxed at source into an ordinary return. The pillar 3a deduction is not inside the withholding scale. It becomes concrete mainly when that assessment applies.",
    brief: ["Keep the 3a certificate.", "The credit must still be in before 31 December.", "This is not an automatic credit."],
    faqs: [{ question: "Does paying a 3a lower withholding tax by itself?", answer: "No. The scale does not contain the deduction. The assessment, where it applies, is the moment it shows up." }],
    blocks: [p(HUB)],
  },
  "3eme-pilier-a-impot-retrait": {
    title: "Tax when a pillar 3a is paid out",
    metaTitle: "Tax on a pillar 3a withdrawal",
    description: "Pillar 3a capital is taxed separately from income. No cantonal rate is published.",
    intro: "When a pillar 3a is paid out, the capital is taxed separately from ordinary income. The rate depends on the canton and the amount. This page does not publish a single rate, because that would be wrong from one canton to the next.",
    brief: ["Separate from income tax.", "Staggering uses several contracts, not a second ceiling.", "No sample tax in francs."],
    faqs: [{ question: "Is there one Swiss withdrawal rate?", answer: "No. Use the cantonal scale for the year of payment. It is not estimated here." }],
    blocks: [p("Staggering: [several contracts](/en/retrait-echelonne-3a/)."), p(HUB)],
  },
  "quel-montant-deductible-3eme-pilier-2022": {
    title: "The 2022 pillar 3a amounts are historical",
    metaTitle: "2022 pillar 3a amounts — historical, not current",
    description: "The 2022 small and large contributions are historical. The current ceilings are the 2026 FSIO figures.",
    intro: "In 2022 the small pillar 3a contribution was 6 883 francs and the large one 34 416 francs. Those 2022 amounts are historical. They are not the current ceiling.",
    brief: [`Current year, 2026: ${petit} and ${grand}.`, "The 2022 line is kept so old links do not teach the old figure as if it were still the law.", PENDING],
    faqs: [{ question: "Can I still deduct the 2022 amount?", answer: "No. Use the ceiling of the year in which the payment is credited. For 2026 that is the FSIO table of 1 January 2026." }],
    blocks: [p(HUB)],
  },
  "a-quoi-sert-le-deuxieme-pilier": {
    title: "What the 2nd pillar is for",
    metaTitle: "What the occupational pension is for",
    description: "The 2nd pillar replaces part of the salary. It also decides which pillar 3a ceiling applies.",
    intro: `The 2nd pillar is funded by employer and employee. On the 2026 FSIO table, compulsory affiliation starts at ${chf(FIGURES.lppEntry)} of annual salary with the same employer. This page keeps the 1 January 2026 thresholds and does not restate other 2027 BVG amounts.`,
    blocks: [p(`Being in or out of that fund sets the pillar 3a ceiling at ${petit} or at 20% of income up to ${grand}. ${PENDING}.`), p(HUB)],
  },
  "ouvrir-un-3eme-pilier-pour-un-frontalier": {
    title: "Opening a third pillar as a cross-border worker",
    metaTitle: "Cross-border worker: opening a pillar 3a",
    description: "Same OASI test as for a resident. The permit is not the key.",
    intro: "A cross-border worker opens a pillar 3a on the same test as anyone else: Swiss earned income subject to OASI. The longer guide is the cross-border page.",
    faqs: [{ question: "Is the ceiling different for cross-border workers?", answer: `No. It is the federal ceiling: ${petit} or up to ${grand} in 2026.` }],
    blocks: [p("Full note: [cross-border third pillar](/en/frontalier-suisse/)."), p(HUB)],
  },
  "quand-commencer-le-3eme-pilier": {
    title: "When to start a third pillar",
    metaTitle: "When to start a pillar 3a",
    description: "You can start once you have income subject to OASI. A missed year before 2025 is not bought back.",
    intro: "Start when earned income is subject to OASI and the payment will not empty your cash reserve. A year missed before 2025 is not bought back. From the 2026 tax year, only gaps from 2025 can be bought back, inside the small contribution.",
    blocks: [p("The buy-back rules: [pillar 3a gaps](/en/rachat-lacunes-3a-2026/)."), p(HUB)],
  },
  "pourquoi-souscrire-au-3eme-pilier": {
    title: "Why take a third pillar",
    metaTitle: "Why a third pillar",
    description: "A federal deduction, a retirement gap, sometimes protection. Not a reason to empty your cash.",
    intro: "People open a third pillar to deduct within the 2026 ceiling, to fill a retirement gap, or to add protection the pension fund does not give. The deduction is not a reason to drain cash you need.",
    blocks: [p(HUB)],
  },
  "3a-impot-cantonal-geneve-2026": {
    title: "Geneva cantonal tax and pillar 3a",
    metaTitle: "Geneva: federal 3a ceiling, cantonal saving",
    description: "Geneva does not raise the 2026 pillar 3a ceiling. Cantonal tax changes the saving, not the right to pay in.",
    intro: `Is the pillar 3a ceiling higher in Geneva than in Lausanne? No. In 2026 it is the federal FSIO ceiling: ${petit} with a 2nd pillar, ${grand} at most without. Cantonal tax changes what you save, not what you may pay in. ${PENDING}.`,
    brief: ["Same federal ceiling.", "Life-premium envelopes are a different rule.", PENDING],
    faqs: [{ question: "Does Geneva add a second 3a maximum?", answer: "No. Article 7 OPP 3 is federal." }],
    blocks: [p("Canton page: [Geneva](/en/3eme-pilier-geneve/)."), p(HUB)],
  },
  "3b-deduction-fribourg": {
    title: "Pillar 3b deduction in Fribourg",
    metaTitle: "Fribourg: life premiums, not a second 3a ceiling",
    description: "Fribourg does not turn pillar 3b into a second OPP 3 ceiling. Some life premiums fit a cantonal envelope.",
    intro: "Can you deduct a pillar 3b in Fribourg the way you deduct a pillar 3a? No. Pillar 3a is national (FSIO). When a Fribourg pillar 3b is useful for tax, it is a life-insurance policy inside a premium envelope, not a second OPP 3 ceiling.",
    brief: [`Orders of magnitude cited for some life premiums: ${chf(FIGURES.fr3bSingle)} for a single person, ${chf(FIGURES.fr3bMarried)} for a couple.`, "The year’s cantonal notice wins.", "Not an automatic credit."],
    faqs: [{ question: "Is this a second pillar 3a?", answer: "No. It does not raise the federal 3a ceiling." }],
    blocks: [p(HUB)],
  },
  "3eme-pilier-canton-vaud": {
    title: "Third pillar in Vaud",
    metaTitle: "Vaud: the federal pillar 3a ceiling, no extra 3a scale",
    description: "Vaud applies article 7 OPP 3. It does not publish a second pillar 3a scale.",
    intro: `Does Vaud have its own pillar 3a ceiling? Not for pillar 3a: Vaud applies article 7 OPP 3. In 2026 the FSIO table gives ${petit} with a 2nd pillar and ${grand} at most without. ${PENDING}. Pillar 3b is not deducted like a federal 3a.`,
    brief: ["No second 3a scale.", "The federal ceiling is the one that counts.", PENDING],
    faqs: [{ question: "Is Vaud’s ceiling higher?", answer: "No. It is the federal ceiling." }],
    blocks: [p(HUB)],
  },
  "choisir-support-3a-2026": {
    title: "Choosing the pillar 3a support",
    metaTitle: "Bank or insurance: the ceiling does not change",
    description: "The 2026 ceiling does not depend on the support. Fees, surrender value and death capital do.",
    intro: `The pillar 3a ceiling does not depend on the support. Bank or insurance, it is the same 2026 amount, ${petit} or ${grand}. What changes: fees, surrender value, death capital and what happens if you stop. ${PENDING}.`,
    brief: ["Same deduction.", "Read the surrender table on a policy.", "No ranking."],
    faqs: [{ question: "Does the support change the FSIO maximum?", answer: "No." }],
    blocks: [p("Longer note: [bank or insurance](/en/3eme-pilier-banque-assurance/)."), p(HUB)],
  },
  "combiner-3a-et-3b-2026": {
    title: "Using pillar 3a and pillar 3b together",
    metaTitle: "Pillar 3a and pillar 3b together",
    description: "Pillar 3a takes the federal deduction. Pillar 3b takes flexibility. There is no official ranking.",
    intro: "Do you have to choose pillar 3a or pillar 3b? Often they fit together. Pillar 3a takes the national deduction (FSIO, article 7 OPP 3). Pillar 3b takes flexibility: beneficiaries, access, sometimes a cantonal premium envelope. There is no official source for a ranking of “the best third pillar”.",
    brief: ["3a does not become unlimited because you also hold a 3b.", "3b does not copy the 3a lock.", PENDING],
    faqs: [{ question: "Does holding both double the federal deduction?", answer: "No. Only pillar 3a has the FSIO ceiling." }],
    blocks: [p(HUB)],
  },
  "depart-suisse-retrait-3a": {
    title: "Leaving Switzerland and withdrawing a pillar 3a",
    metaTitle: "Leaving Switzerland: early payment of pillar 3a",
    description: "A definitive departure is a legal reason for early payment. Exit tax is not in the ceiling PDF.",
    intro: "Can you withdraw a pillar 3a when you leave Switzerland? Yes. A definitive departure is a legal reason for early payment (FSIO). It has to be a real departure. Exit tax, and the difference between EU/EFTA and the rest of the world, are not in the ceiling PDF.",
    brief: ["Definitive departure, not a short stay abroad.", "The 2nd pillar has its own rules.", "No exit-tax rate is published here."],
    faqs: [{ question: "Is the withdrawal tax-free because I leave?", answer: "No. Departure opens the payment. Tax on the way out still has to be checked. It is not estimated here." }],
    blocks: [p(HUB)],
  },
  "frontalier-avs-3a-conditions": {
    title: "OASI conditions for a cross-border pillar 3a",
    metaTitle: "Cross-border workers: OASI is the key to pillar 3a",
    description: "A cross-border worker can open a pillar 3a if Swiss earned income is subject to OASI.",
    intro: "Can a cross-border worker open a pillar 3a? Yes, if earned income in Switzerland is subject to OASI. The permit and the EU place of residence do not open the 3a. OASI liability does. Source: FSIO and FTA circular no. 18.",
    brief: ["Same federal ceiling as a resident in that situation.", "Without Swiss OASI, pillar 3a stays closed.", PENDING],
    faqs: [{ question: "Is a G permit enough?", answer: "No. The test is OASI on the Swiss earned income." }],
    blocks: [p(HUB)],
  },
  "rachat-2e-pilier-avec-3a": {
    title: "Using a pillar 3a to fund a pension-fund buy-back",
    metaTitle: "Pillar 3a toward the 2nd pillar",
    description: "A 3a can be transferred to a pension fund to fund a buy-back, under the occupational-pension rules. The reverse direct transfer is not possible.",
    intro: "Under the conditions set for a buy-back in the occupational pension, a pillar 3a balance can be transferred directly to a pension fund to fund that buy-back. The movement is 3a toward the 2nd pillar. The reverse — 2nd pillar or vested benefits toward a 3a — is not possible by direct transfer.",
    brief: ["Direction: 3a to the pension fund.", "Not the same as the 3a gap buy-back.", "The pension fund’s own buy-back rules still apply."],
    faqs: [
      { question: "Can vested benefits move straight into a 3a?", answer: "No. That direct transfer is not available." },
      { question: "Is this the 2026 pillar 3a gap buy-back?", answer: "No. The gap buy-back is a new 3a payment for a missing year from 2025. This page is a transfer into the pension fund." },
    ],
    blocks: [p("Gap buy-back: [pillar 3a gaps](/en/rachat-lacunes-3a-2026/). Vested benefits: [not a 3a](/en/libre-passage-lpp/)."), p(HUB)],
  },
  "retrait-3a-vs-3b-2026": {
    title: "Withdrawing pillar 3a or pillar 3b",
    metaTitle: "Withdrawal: pillar 3a is locked, pillar 3b follows the contract",
    description: "Pillar 3a leaves only for legal reasons and is taxed apart from income. Pillar 3b follows the contract.",
    intro: "No: pillar 3a capital is tied and comes out only for reasons the law provides, then it is taxed apart from ordinary income. Pillar 3b is flexible provision: withdrawal, fees and tax depend on the support and, for insurance, on the contract.",
    brief: ["3a reasons include retirement, home you live in, definitive departure, self-employment, disability.", "3b is not that list.", "No cantonal tax rate is printed."],
    faqs: [
      { question: "Can I withdraw a 3a whenever I want?", answer: "No. The reasons are legal. Wanting the money is not one of them." },
      { question: "Is a 3b withdrawal taxed like a 3a?", answer: "Not automatically. A bank balance and a life policy do not follow the same tax story, and the canton matters." },
    ],
    blocks: [p(HUB)],
  },
  "retraite-avs-21-femmes-3a": {
    title: "OASI 21, women’s reference age, and pillar 3a",
    metaTitle: "OASI 21 and pillar 3a: the ceiling does not move with the reform",
    description: "OASI 21 gradually raises women’s reference age from 64 to 65. It does not change the 2026 pillar 3a ceiling.",
    intro: `OASI 21 gradually raises women’s reference age from 64 to 65. That changes the retirement horizon and the contribution period, not the 2026 pillar 3a ceiling: ${petit} and ${grand} according to the FSIO. ${PENDING}.`,
    brief: ["Reference age is not the 3a ceiling.", "The ceiling still depends on 2nd-pillar affiliation.", PENDING],
    faqs: [{ question: "Does the reform raise the 3a maximum?", answer: "No. The maximum stays the FSIO figure for the year of the payment." }],
    blocks: [p(HUB)],
  },
  "tableau-ofas-montants-avs-lpp-3a": {
    title: "How to read the FSIO amounts table",
    metaTitle: "FSIO table: OASI, BVG and pillar 3a",
    description: "The comparison does not set the ceilings. It reads the FSIO PDF of amounts at 1 January 2026.",
    intro: "The comparison does not decide the ceilings. It reads the same PDF as the pension funds: amounts valid on 1 January 2026. That table links the first, second and third pillars. It does not yet state the next year.",
    brief: [`OASI full pension: ${chf(FIGURES.avsMinMonthly)} to ${chf(FIGURES.avsMaxMonthly)} a month.`, `BVG entry: ${chf(FIGURES.lppEntry)}.`, `Pillar 3a: ${petit} / ${grand}.`, PENDING],
    faqs: [{ question: "Is a build date a verification?", answer: `No. The editorial check cited here is ${REVIEW}.` }],
    blocks: [p(HUB)],
  },
  "tou-impot-source-3a": {
    title: "Withholding tax and pillar 3a",
    metaTitle: "Withholding tax: the 3a deduction is not in the scale",
    description: "Paying a pillar 3a does not by itself cut withholding tax. A subsequent ordinary assessment is where it usually shows.",
    intro: "Why pay a pillar 3a if you are taxed at source? Because the deduction is not in the withholding scale. It becomes concrete mainly if a subsequent ordinary assessment applies, or later, depending on the canton. It is not an automatic credit “like a resident”.",
    brief: ["Pay before 31 December if you want the year.", "Keep the certificate.", "The ceiling stays the federal one."],
    faqs: [{ question: "Should I wait for the assessment before paying?", answer: "The credit date still has to fall in the tax year you want. Waiting until January misses that year." }],
    blocks: [p("Assessment: [subsequent ordinary assessment](/en/taxation-ordinaire-ulterieure/)."), p(HUB)],
  },
  "deduction-3e-pilier-impot-a-la-source": {
    title: "Pillar 3a deduction under withholding tax",
    metaTitle: "Pillar 3a deduction when you are taxed at source",
    description: "A pillar 3a payment is not in the withholding-tax scale. The deduction goes through a subsequent ordinary assessment, by 31 March.",
    intro: "Yes, a pillar 3a is deductible for someone taxed at source in Switzerland, but not in the scale the employer withholds. The deduction goes through a subsequent ordinary assessment: mandatory or on request for residents, and on request for a quasi-resident living abroad if the conditions are met. Without that procedure, no extra deduction is granted.",
    brief: [
      "The monthly scale does not include the real pillar 3a payment.",
      "Residents at CHF 120,000 of gross employment income, or their spouse, must file.",
      "Otherwise the request is due by 31 March of the following year.",
      "A quasi-resident needs at least 90% of worldwide household income taxable in Switzerland.",
      "2026 ceilings stay 7,258 CHF with a 2nd pillar, and 20% up to 36,288 CHF without.",
      "From 1 January 2027 the Federal Council set 7,373 and 36,864 CHF. Those figures do not apply to a 2026 payment.",
    ],
    faqs: [
      { question: "Is pillar 3a deductible under withholding tax?", answer: "Yes, for someone who lives in Switzerland and has paid in. The route is not the monthly scale. It is the subsequent ordinary assessment, mandatory or on request." },
      { question: "Why does net pay not fall after the payment?", answer: "The employer applies flat amounts, not the real contribution (Federal Direct Tax Act, art. 85). The effect shows in the assessment, which credits the tax already withheld." },
      { question: "From what income is the assessment mandatory?", answer: "From CHF 120,000 of gross employment income, or from income that is not taxed at source. For a couple, one spouse’s income is enough. Wealth thresholds depend on the canton." },
      { question: "What is the deadline for tax year 2026?", answer: "The payment must be credited by 31 December 2026. The assessment request is due by 31 March 2027, or with the departure return. The federal tax administration treats that date as a forfeiture deadline." },
      { question: "Can a cross-border worker always deduct pillar 3a in Switzerland?", answer: "No. The income must be taxable in Switzerland under the treaty, and the 90% test must be met, spouse included. Cross-border workers covered by the Switzerland–Italy agreement have been excluded since 1 January 2024." },
      { question: "Can the assessment raise the tax?", answer: "Yes. Withholding is credited without interest, then the balance is due or refunded. A filed request cannot be withdrawn." },
    ],
    blocks: [
      h2("Why the deduction is not in the scale"),
      p("The employer’s withholding is capped at flat professional expenses, insurance premiums and family charges. The tied-pension contribution is a separate deduction. It is not applied to the month’s salary. Since 1 January 2021 the federal tax administration requires a subsequent ordinary assessment, not a simple scale correction. Geneva described this on 13 March 2026."),
      h2("Mandatory or on request"),
      p("For people living in Switzerland, the assessment is mandatory from CHF 120,000 of gross employment income, or if there is income not taxed at source. One spouse is enough; the two salaries are not added together. It then continues until withholding tax ends. Without that trigger, the request is due by 31 March of the next year, and when leaving Switzerland with the departure return."),
      h2("Quasi-resident"),
      p("Someone living abroad can ask, each tax year, if at least 90% of the household’s worldwide gross income is taxable in Switzerland. The request is written and irrevocable for that year. It does not by itself create the status. French cross-border workers outside Geneva are often taxed in France on that salary, which lowers the Swiss share. Italy-agreement cross-border workers are excluded."),
      h2("How much can be deducted"),
      p("For 2026 the federal tax administration publishes 7,258 CHF with a 2nd pillar and 36,288 CHF without. A payment counts only if it is credited by 31 December of that year."),
      p("On 2 October 2026 the [Federal Council](https://www.admin.ch/fr/newnsb/BqB41FVYi5FB) set the amounts from 1 January 2027 at 7,373 and 36,864 CHF. They are the latest published ceilings. They do not apply to a 2026 payment."),
      p("Sources: [withholding tax](https://www.estv.admin.ch/fr/impot-a-la-source), [3a ceilings](https://www.estv.admin.ch/fr/taux-interet-deductions-maximales-pilier-3a-impot-federal-direct), [Federal Direct Tax Act](https://www.fedlex.admin.ch/eli/cc/1991/1184_1184_1184/fr) and [OIS](https://www.fedlex.admin.ch/eli/cc/2018/274/fr). Next: [tax deductions](/en/deductions-fiscales-3eme-pilier/), [subsequent ordinary assessment](/en/taxation-ordinaire-ulterieure/), [cross-border workers](/en/frontalier-suisse/)."),
      p(FORM),
      p(HUB),
    ],
  },
  "versement-3a-avant-31-decembre-2026": {
    title: "Credit the pillar 3a before 31 December",
    metaTitle: "Pillar 3a payment: the credit date counts",
    description: "An order dated 28 December can fall into the next year if the account is not credited in time.",
    intro: "A pillar 3a order given on 28 December can fall into the next year if the bank or insurer does not credit the account in time. The FSIO says the deduction follows the credit date, not the date of the order.",
    brief: ["31 December is the credit deadline for that tax year.", "Many institutions stop orders in mid-December.", `The 2026 ceiling is still ${petit} or up to ${grand}.`],
    faqs: [{ question: "Does the order date save the year?", answer: "No. If the money arrives in January, it counts for the following year, under that year’s ceiling." }],
    blocks: [p(HUB)],
  },
};
